# Generated by Django 2.0.7 on 2018-08-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_auto_20180822_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
