# Generated by Django 2.0.7 on 2018-08-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_auto_20180828_0919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('product', 'project')},
        ),
    ]
