# Generated by Django 2.0.7 on 2018-08-30 10:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_auto_20180830_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='about',
            field=tinymce.models.HTMLField(null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
