# Generated by Django 2.0.7 on 2018-09-10 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0010_auto_20180831_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('project', 'version')},
        ),
    ]
