# Generated by Django 2.0.7 on 2018-09-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0011_auto_20180910_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
