# Generated by Django 2.0.7 on 2018-09-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0012_auto_20180910_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='publish_mode',
            field=models.BooleanField(default=True),
        ),
    ]
